name: cogo
description: "COGO"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #router
  go_router: ^13.1.0

  # network
  dio: ^5.3.2

  # status manage
  provider: ^6.0.5

  #splash
  flutter_native_splash: ^2.4.1

  #sharedprefernences
  shared_preferences: ^2.0.7

  #svg
  flutter_svg: ^2.0.10+1

  #날 형식 변환
  intl: ^0.18.0

  #구글 로그인
  google_sign_in: ^6.2.1

  #토큰 저장소
  flutter_secure_storage: ^8.0.0
  flutter_config: ^2.0.2

  #DI
  get_it: ^7.7.0

  #모델 만들기
  json_annotation: ^4.9.0

  #달력
  table_calendar: ^3.0.9

  # 직렬화 Freezed
  freezed_annotation: ^2.0.3

  #토스트 메시지
  fluttertoast: ^8.0.9

  # 애니메이션 로티
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  freezed: ^2.0.3
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/navigator/
    - assets/icons/3d_img/
    - assets/icons/button/
    - assets/image/
    - assets/lottie/

  fonts:
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
    - family: PretendardLight
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf

flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen
  image: assets/image/logo.svg # Optional: static image
  android:fullscreen: true # Optional: make it fullscreen
  ios:fullscreen: true # Optional: make it fullscreen